# Virtual A/B device
FOX_VIRTUAL_AB_DEVICE := 1

# UI Related
OF_SCREEN_H := 1600
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 1
OF_ALLOW_DISABLE_NAVBAR := 0

# Partition tools
OF_ENABLE_ALL_PARTITION_TOOLS := 1

# VendorBoot
FOX_VENDOR_BOOT_RECOVERY := 1
FOX_INSTALLER_VENDOR_BOOT_RAMDISK_INSTALL := 1

# Keymaster
OF_DEFAULT_KEYMASTER_VERSION := 4.1

# Additional configs
OF_SUPPORT_VBMETA_AVB2_PATCHING := 1
OF_FORCE_PREBUILT_KERNEL := 1

OF_MAINTAINER := Andriann.